### ISSUE TITLE
Shaders underwater

### ISSUE THREAD

**Issue by Tsunai001** [ItsPasi/natural-motionblur-fabric#3]
Are you able to add a function that automatically toggles the mod off when shaders are enabled? (most shaders have motion blur) as underwater with Complementary Shaders is so foggy and dark you cannot see
![image](https://github.com/user-attachments/assets/c5c404c9-fb5d-4494-8811-9a56780a6585)

**Comment by ItsPasi** [comment]
I will try doing that as soon as I have time, but it might take a while. For now just switch it off via a keybind when turning on shaders.

**Comment by Tsunai001** [comment]
awesome, thank you for response

**Comment by ItsPasi** [comment]
[naturalmotionblur-1.1.1+mc1.20.6.zip](https://github.com/user-attachments/files/16316529/naturalmotionblur-1.1.1%2Bmc1.20.6.zip)

Can you try this version and check if you notice any bugs?

**Comment by Tsunai001** [comment]
I was already using that exact version in the screenshot

**Comment by ItsPasi** [comment]
Its a dev version I was too lazy to change the file name

**Comment by Tsunai001** [comment]
yep fixed thank you heaps

**Comment by ItsPasi** [comment]
Alright I will close the issue and update the mod soon :)
